config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "videos#index"
  resources :videos, only: [:show] do
    get :about, on: :collection
    resources :videocomments, only: :create
  end
  resources :posts, only: [:index, :create, :new, :show] do
    get :createpage, on: :collection
    resources :comments, only: :create
  end
  resources :users, only: [:show, :edit, :update] do
    collection do
      get :createpage
      get :editpage
    end
  end
  post   '/like/:comment_id', to: 'likes#like',   as: 'like'
  delete '/like/:comment_id', to: 'likes#unlike', as: 'unlike'
  post   '/videolike/:videocomment_id', to: 'videolikes#like',   as: 'videolike'
  delete '/videolike/:videocomment_id', to: 'videolikes#unlike', as: 'videounlike'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :likes, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  validates :comment, presence: true, unless: :image?
  mount_uploader :image, ImagesUploader
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :posts
  has_many :videos
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :comment, counter_cache: :likes_count
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :game_id, presence: true
  has_many :comments
  belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :comments
  has_many :videocomments
  has_many :likes, dependent: :destroy
  has_many :like_comments, through: :likes, source: :comment
  has_many :videolikes, dependent: :destroy
  has_many :videolike_comments, through: :videolikes, source: :videocomment

  validates :nickname, presence: true, length: { maximum: 6 }
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :game
  has_many :videocomments
end

app/models/videocomment.rb
class Videocomment < ApplicationRecord
  belongs_to :user
  belongs_to :video
  has_many :videolikes, dependent: :destroy
  has_many :videoliking_users, through: :videolikes, source: :user

  validates :comment, presence: true
end

app/models/videolike.rb
class Videolike < ApplicationRecord
  belongs_to :videocomment, counter_cache: :likes_count
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end

  private
  def after_update_path_for(resource)
    editpage_users_path
  end

  def after_sign_up_path_for(resource)
    createpage_users_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    Comment.create(comment_params)
    redirect_to "/posts/#{params[:post_id]}"
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :image).merge(user_id: current_user.id, post_id: params[:post_id], likes_count: 0)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def like
    like = current_user.likes.new(comment_id: params[:comment_id])
    like.save
    set_variables
  end

  def unlike
    like = current_user.likes.find_by(comment_id: params[:comment_id])
    like.destroy
    set_variables
  end

  private

  def set_variables
    @comment = Comment.find(params[:comment_id])
    @id_name = "#like-link-#{@comment.id}"
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @search = Post.ransack(params[:q])
    if params[:game_id]
      @posts = Post.where(game_id: params[:game_id]).page(params[:page]).per(10)
    else
      @posts = @search.result.includes(:game).order("created_at DESC").page(params[:page]).per(10)
    end
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to createpage_posts_path
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  private
  def post_params
    params.require(:post).permit(:title, :game_id)
  end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:show]

  def show
    @nickname = current_user.nickname
  end

  private
  def correct_user
    user = User.find(params[:id])
    if current_user != user
      redirect_to root_path
    end
  end

end

app/controllers/videocomments_controller.rb
class VideocommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    Videocomment.create(videocomment_params)
    set_variables
  end

  private
  def videocomment_params
    params.require(:videocomment).permit(:comment).merge(user_id: current_user.id, video_id: params[:video_id], likes_count: 0)
  end

  def set_variables
    @video = Video.find(params[:video_id])
    @videocomments = @video.videocomments.includes(:user)
  end

end

app/controllers/videolikes_controller.rb
class VideolikesController < ApplicationController

  def like
    like = current_user.videolikes.new(videocomment_id: params[:videocomment_id])
    like.save
    set_variables
  end

  def unlike
    like = current_user.videolikes.find_by(videocomment_id: params[:videocomment_id])
    like.destroy
    set_variables
  end

  private

  def set_variables
    @videocomment = Videocomment.find(params[:videocomment_id])
    @id_name = "#like-link-#{@videocomment.id}"
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :videos_search

  def index
    if params[:game_id]
      @videos = Video.where(game_id: params[:game_id]).page(params[:page]).per(3)
    else
      @videos = @search.result.includes(:game).order("created_at DESC").page(params[:page]).per(3)
    end
  end

  def show
    @video = Video.find(params[:id])
    @videocomment = Videocomment.new
    @videocomments = @video.videocomments.includes(:user).order("created_at ASC")
  end

  private

  def videos_search
    @search = Video.ransack(params[:q])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def comment_change(comment_count)
    if comment_count >= 4
      "comment4"
    elsif comment_count >= 3
      "comment3"
    elsif comment_count >= 2
      "comment2"
    elsif comment_count >= 1
      "comment1"
    else
      "comment0"
    end
  end

  def videocomment_change(comment_count)
    if comment_count >= 4
      "comment4"
    elsif comment_count >= 3
      "comment3"
    elsif comment_count >= 2
      "comment2"
    elsif comment_count >= 1
      "comment1"
    else
      "comment0"
    end
  end

end

app/views/layouts/_header.html.slim
header
  .left-bar
    .left-bar__title
      = link_to root_path
        = image_tag "favicon.ico"
        p WhiteWall
  .right-bar
    .right-bar__about
      = link_to "About","/videos/about"
    - if user_signed_in?
      .right-bar__login
        = link_to "ログアウト",destroy_user_session_path, method: :delete
      .right-bar__user
        = link_to current_user.nickname,"/users/#{current_user.id}"
    - else
      .right-bar__login
        = link_to "ログイン",new_user_session_path
      .right-bar__user
        = link_to "新規登録",new_user_registration_path

app/views/layouts/_sidebar-left.html.slim
= javascript_include_tag "jquery.sidebar.min.js"
= javascript_include_tag "sidebar.js"
.btn data-action="toggle" data-side="left"
  | ♦
.sidebar.left
  .title
    = link_to "掲示板一覧", posts_path
  .game
    .game__name
      = link_to "civilization5", posts_path(game_id: 1)
    .game__name
      = link_to "WoWs", posts_path(game_id: 2)
    .game__name
      = link_to "Wot", posts_path(game_id: 3)
    .game__name
      = link_to "東方蟒酒宴", posts_path(game_id: 4)
    .game__name
      = link_to "aoe2", posts_path(game_id: 5)
  .title
      = link_to "動画一覧", root_path
  .game
    .game__name
      = link_to "civilization5", root_path(game_id: 1)
    .game__name
      = link_to "WoWs", root_path(game_id: 2)
    .game__name
      = link_to "Wot", root_path(game_id: 3)
    .game__name
      = link_to "東方蟒酒宴", root_path(game_id: 4)
    .game__name
      = link_to "aoe2", root_path(game_id: 5)

app/views/layouts/application.html.slim
doctype html
html
  head
    = favicon_link_tag
    title
      | WhiteWall
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'


    
  body
    = render "layouts/header"
  .wrapper
    = yield

app/views/likes/_like.html.slim
div class="#{comment_change(comment.likes_count)}"
  = comment.comment
  br
  = image_tag "#{comment.image}" if comment.image.present?
  br
  - if current_user.likes.find_by(comment_id: comment.id)
    = link_to unlike_path(comment.id), method: :delete, remote: true do
      .iine__button
        |❤️ #{comment.likes_count}
  - else
    = link_to like_path(comment.id), method: :post, remote: true do 
      .iine__button
        |♡️ #{comment.likes_count}

app/views/likes/like.js.slim
|$("#{@id_name}").html("#{escape_javascript(render("likes/like", comment: @comment))}");

app/views/likes/unlike.js.slim
|$("#{@id_name}").html("#{escape_javascript(render("likes/like", comment: @comment))}");

app/views/posts/createpage.html.slim
.create
  p 掲示板の作成が完了しました。
  .create__btn
    = link_to "投稿された掲示板を確認する",posts_path

app/views/posts/index.html.slim
= render "layouts/sidebar-left"
.post
  .post-title
    .post-enpty
    h1 掲示板一覧
    .post-new
      = link_to "掲示板作成へ",new_post_path
  .post-search
    = search_form_for @search, url: posts_path do |f|
      = f.search_field :title_cont, placeholder: "掲示板を検索"
  .post-area
    - @posts.each do |post|
      .content
        .content__left
          .content__left__image
            = image_tag "#{post.game.gameimage}"
        .content__right
          .content__right__top
            = post.game.gametitle
        .content__right__bottom
          .content__right__bottom__title
            = link_to post.title, post_path(post.id)
  = paginate(@posts)

app/views/posts/new.html.slim
.content-title
  h1 新規掲示板の作成
  p ゲームの種類を選択してください
  .content-field
    = form_with model: @post, class: "form", local: true do |f|
      .content-field__radio
        = f.radio_button :game_id, "1"
        = f.radio_button :game_id, "2"
        = f.radio_button :game_id, "3"
        = f.radio_button :game_id, "4"
        = f.radio_button :game_id, "5"
      .content-field__image
        .content-field__image__game
          = image_tag "civ5.jpg"
        .content-field__image__game
          = image_tag "WorldOfWarships.jpg"
        .content-field__image__game
          = image_tag "WoT.jpg"
        .content-field__image__game
          = image_tag "東方蟒酒宴.jpg"
        .content-field__image__game
          = image_tag "aoc2.jpg"
      p 掲示板のタイトルを入力してください
      .content-field__title
        = f.text_field :title, placeholder: "掲示板のタイトル"
      .content-field__btn
        = f.submit "掲示板作成"

app/views/posts/show.html.slim
= render "layouts/sidebar-left"
.post-show
  .post-index
    .post-title
      = @post.title
    .post-area
      = link_to "掲示板へ戻る",posts_path
  .news
    - @comments.each.with_index(1) do |comment, i|
      .txt
        .txt__number
          = i
        .txt__name
          = comment.user.nickname
        .txt__date
          = comment.created_at.to_s
      .comment
        .like-link id="like-link-#{comment.id}"
          = render 'likes/like', comment: comment
  .message
    .message__area
      = form_with model: [@post,@comment],class: "form", local: true do |f|
        .message__area__txt
          p コメント
          = f.text_area :comment, placeholder: "コメント"
          label.label
            = icon('fa', 'image')
            = f.file_field :image, class: "hoge"
          .submit-btn
            = f.submit "投稿する"

app/views/users/createpage.html.slim
.create
  p ユーザー登録が完了しました。
  .create__btn
    = link_to "メインページに戻る",root_path

app/views/users/editpage.html.slim
.create
  p ユーザー編集が完了しました。
  .create__btn
    = link_to "ユーザー詳細ページに戻る","/users/#{current_user.id}"

app/views/users/show.html.slim
.user-show
  .area
    .field
      p ユーザー名
      .field__user-data
        =@nickname
  .area
    .field
      p メールアドレス
      .field__user-data
        =current_user.email
  .actions
    = link_to "ユーザー編集","/users/edit"

app/views/videocomments/_videocomment.html.slim
.txt
  .txt__number
    = "#{videocomment_counter + 1}"
  .txt__name
    = videocomment.user.nickname
  .txt__date
    = videocomment.created_at.to_s
.comment
  .like-link id="like-link-#{videocomment.id}"
    = render 'videolikes/like', videocomment: videocomment

app/views/videocomments/create.js.slim
|$(".news").html("#{escape_javascript(render partial: 'videocomments/videocomment', collection: @videocomments)}");
|$('.news').animate({ scrollTop: $('.news')[0].scrollHeight});

app/views/videolikes/_like.html.slim
div class="#{videocomment_change(videocomment.likes_count)}"
  = videocomment.comment
  br
  - if current_user.videolikes.find_by(videocomment_id: videocomment.id)
    = link_to videounlike_path(videocomment.id), method: :delete, remote: true do
      .iine__button
        |❤️ #{videocomment.likes_count}
  - else
    = link_to videolike_path(videocomment.id), method: :post, remote: true do 
      .iine__button
        |♡️ #{videocomment.likes_count}

app/views/videolikes/like.js.slim
|$("#{@id_name}").html("#{escape_javascript(render("videolikes/like", videocomment: @videocomment))}");

app/views/videolikes/unlike.js.slim
|$("#{@id_name}").html("#{escape_javascript(render("videolikes/like", videocomment: @videocomment))}");

app/views/videos/_videos.html.slim
.video-all
  h1 ストラテジー動画一覧
  .video-movie
    - @videos.each do |video|
      .video-content
        .video-content__top
          img src="#{video.thumbnail}"
        .video-content__bottom
          .video-content__bottom__left
            = image_tag "#{video.game.gameimage}"
          .video-content__bottom__right
            .video-content__bottom__right__title
              = link_to video.title, video_path(video.id)
            .video-content__bottom__right__views-date
              | 再生数#{video.views}回・#{video.created_at}
  = paginate(@videos)

app/views/videos/about.html.slim
= render "layouts/sidebar-left"
.about
  p こちらはストラテジーゲームプレイヤーを対象としたコミュニティサイトです。
  p みんなで掲示板、動画などを利用して技術を向上させましょう!

app/views/videos/index.html.slim
.mainpage
  h1 WhiteWall
  p 戦うための戦略がここにある!
  p こちらはストラテジーゲームプレイヤーを対象としたコミュニティサイトです。
  p みんなで掲示板、動画などを利用して技術を向上させましょう!
  = search_form_for @search, url: root_path do |f|
    = f.search_field :title_cont, placeholder: "動画を検索"
= render "layouts/sidebar-left"
= render "videos"
                

app/views/videos/show.html.slim
= render "layouts/sidebar-left"
.video-show
  .video-show__concept
    .video-show__concept__search
      = search_form_for @search, url: root_path do |f|
        = f.search_field :title_cont, placeholder: "動画を検索"
    .video-show__concept__area
      iframe allow=("accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture") allowfullscreen="" frameborder="0" height="472.5" src="https://www.youtube.com/embed/#{@video.url}" width="840"
    .video-show__concept__description
      .video-show__concept__description__title
        = @video.title
      .video-show__concept__description__views-date
        | 再生数#{@video.views}回・#{@video.created_at}
      .video-show__concept__description__text
        = @video.description
  .news
    = render partial: 'videocomments/videocomment', collection: @videocomments
  .message
    .message__area
      = form_with model: [@video,@videocomment],class: "form" do |f|
        .message__area__txt
          p コメント
          = f.text_area :comment, placeholder: "コメント"
          .submit-btn
            = f.submit "投稿する"